spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
          replication-factor: 1
          configuration:
            auto-offset-reset: latest
      bindings:
        contact-in:
          destination: contact-deprecated
          group: input-group-N
          contentType: application/json
          consumer:
            max-attempts: 1
            autoCommitOffset: true
            autoCommitOnError: false
        contact-out:
          destination: contact-deprecated
          group: input-group-N
          contentType: application/json
          consumer:
            max-attempts: 1
            autoCommitOffset: true
            autoCommitOnError: false
        client-out:
          destination: client-deprecated
          group: input-group-N
          contentType: application/json
          consumer:
            max-attempts: 1
            autoCommitOffset: true
            autoCommitOnError: false
